#include "SteamCoreInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs.h"

USteamCoreInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs::USteamCoreInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs() {
}

USteamCoreInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs* USteamCoreInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs::RequestEligiblePromoItemDefinitionsIDsAsync(UObject* WorldContextObject, FSteamID SteamID, float Timeout) {
    return NULL;
}

void USteamCoreInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs::HandleCallback(const FSteamInventoryEligiblePromoItemDefIDs& Data, bool bWasSuccessful) {
}


