#include "SteamCoreUserStatsAsyncActionDownloadLeaderboardEntriesForUsers.h"

USteamCoreUserStatsAsyncActionDownloadLeaderboardEntriesForUsers::USteamCoreUserStatsAsyncActionDownloadLeaderboardEntriesForUsers() {
}

void USteamCoreUserStatsAsyncActionDownloadLeaderboardEntriesForUsers::HandleCallback(const FLeaderboardScoresDownloadedForUsers& Data, bool bWasSuccessful) {
}

USteamCoreUserStatsAsyncActionDownloadLeaderboardEntriesForUsers* USteamCoreUserStatsAsyncActionDownloadLeaderboardEntriesForUsers::DownloadLeaderboardEntriesForUsersAsync(UObject* WorldContextObject, FSteamLeaderboard SteamLeaderboard, TArray<FSteamID> Users, float Timeout) {
    return NULL;
}


